In [12]:
from scipy.spatial.transform import Rotation
import numpy as np
import math

In [13]:
### x1がy軸に、x2がxy平面上に落ちるような回転行列Rを算出する
x1 = np.array([5, 100, 10])
x2 = np.array([10, 20, 5])
ax = np.array([1,0,0])
ay = np.array([0,1,0])

In [14]:
#x1がy軸に一致するように回転する
nx1 = x1 / np.linalg.norm(x1)
axis1 = np.cross(nx1, ay)
nax1 = axis1 / np.linalg.norm(axis1)
angle1 = math.acos(nx1.dot(ay))
rot1 = Rotation.from_rotvec(nax1 * angle1)

x1b = rot1.apply(x1)
x2b = rot1.apply(x2)

x2c = np.array([x2b[0], 0, x2b[2]])
nx2c = x2c / np.linalg.norm(x2c)

#x2cがxy平面に落ちるような回転行列Rを算出する
angle2 = math.acos(nx2c.dot(ax))
rot2 = Rotation.from_rotvec(ay * angle2)
rot = rot2 * rot1

rot2.apply(x2b)

array([ 9.45750731e+00,  2.08699678e+01, -2.22044605e-15])

In [15]:
x1_new = rot.apply(x1)
x2_new = rot.apply(x2)
print(x1_new)
print(x2_new)

[-2.48689958e-14  1.00623059e+02 -2.33146835e-14]
[ 9.45750731e+00  2.08699678e+01 -3.10862447e-15]
